# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

COPY ./shared/CopilotAgentOpsMcp.Shared /source/shared/CopilotAgentOpsMcp.Shared
COPY ./hybridapp/src/CopilotAgentOpsMcp.HybridApp /source/hybridapp/src/CopilotAgentOpsMcp.HybridApp

WORKDIR /source/hybridapp/src/CopilotAgentOpsMcp.HybridApp

ARG TARGETARCH
RUN case "$TARGETARCH" in \
      "amd64") RID="linux-musl-x64" ;; \
      "arm64") RID="linux-musl-arm64" ;; \
      *) RID="linux-musl-x64" ;; \
    esac && \
    dotnet publish -c Release -o /app -r $RID --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS final

WORKDIR /app

COPY --from=build /app .

USER $APP_UID

ENTRYPOINT ["dotnet", "CopilotAgentOpsMcp.HybridApp.dll"]
